name: Publish ic-websocket-cdk-mo

# only run when a release is published
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: dfinity/setup-dfx@main
        with:
          dfx-version: 0.24.1

      - name: install mops
        run: npm i ic-mops -g

      - name: install moc
        run: npx mocv use latest

      - name: publish on mops
        run: |
          mops import-identity --no-encrypt -- "${DFX_IDENTITY_PEM}"
          mops publish
        env:
          DFX_IDENTITY_PEM: ${{ secrets.DFX_IDENTITY_PEM }}
